<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Auth" Version="1.72.0" />
    <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="8.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RentACar.Interfaces\RentACar.Interfaces.csproj" />
    <ProjectReference Include="..\RentACar.Models\RentACar.Models.csproj" />
    <ProjectReference Include="..\RentACar.Repository\RentACar.Repository.csproj" />
    <ProjectReference Include="..\RentACar.ViewModel\RentACar.ViewModel.csproj" />
  </ItemGroup>

</Project>
